# Generated by Django 4.1.2 on 2022-10-12 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('movie_discription', models.TextField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visibility', models.ManyToManyField(blank=True, related_name='visibility', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
