# Generated by Django 4.1.2 on 2022-10-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_postmanagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostManagement',
        ),
    ]
