# Generated by Django 4.1.2 on 2022-10-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0004_postmanagement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmanagement',
            old_name='movie_discription',
            new_name='movie_description',
        ),
    ]
